---
sidebar: sidebar 
permalink: concept_working_with_inventory_file.html 
keywords: inventory file, file format 
summary: Stellt Informationen zum Arbeiten mit der Bestandsdatei bereit. 
---
= Aktualisieren Sie die Inventardatei für das AFF und FAS -Firmware-Update.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Inventardatei besteht aus den LIFs für das Cluster-Management der Systeme, die für Firmware-Updates qualifiziert sind. Er enthält gegebenenfalls eine Liste der Cluster mit einem Dateinamen der Festplatten- und Shelf-Firmware.

Für das Update der Service Processor-Firmware sind Node-Hostnamen und SP/BMC IP in der Bestandsdatei enthalten.



== Inventurdateiformat

Im Folgenden finden Sie ein Beispiel für eine Bestandsdateiformat mit Updates der Festplatten- und Shelf-Firmware:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip

  - clustername: <cluster management LIF-2>
    disk_fw_file: all.zip
    sp_nodes:
    - hostname: <node hostname 1>
      sp_fw_file: SP_FW_308-03990_11.5.zip
      sp_fw_type: bmc
      sp_fw_ver: '11.5'
      sp_ip: <BMC IP>
    - hostname: <node hostname 2>
      sp_fw_file: SP_FW_308-03991_5.8.zip
      sp_fw_type: sp
      sp_fw_ver: '5.8'
      sp_ip: <SP IP>
----
Im Beispiel gelten Updates der Shelf- und Festplatten-Firmware sowohl für Cluster-1 als auch für Festplatten- und SP/BMC-Firmware auf Cluster-2.



== Löschen eines Clusters aus der Bestandsdatei

Wenn Sie keine Firmware-Updates für ein bestimmtes Cluster anwenden möchten, können Sie das Cluster aus der Bestandsdatei entfernen.

Wenn Sie beispielsweise keine Festplatten-Firmware-Updates auf Cluster-2 anwenden möchten, können Sie sie mit dem folgenden Befehl aus der Bestandsdatei entfernen:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
    shelf_fw_file: all_shelf_fw.zip
----
Sie können beobachten, dass alle Daten für Cluster-2 gelöscht wurden.

Wenn Sie nur Aktualisierungen der Festplatten-Firmware auf Cluster-1 und nicht auf Updates der Shelf-Firmware anwenden möchten, können Sie dies mit dem folgenden Befehl durchführen:

[listing]
----
clusters:
  - clustername: <cluster management LIF-1>
    disk_fw_file: all.zip
----
Sie sehen, dass der Schlüssel „_Shelf_fw_file_“ und der Wert aus „Cluster-1“ entfernt wurden.


NOTE: Das manuelle Hinzufügen von Clustern oder Controllern wird nicht unterstützt.
