---
sidebar: sidebar 
permalink: concept_autosupport.html 
keywords: AutoSupport 
summary: Bietet einen Überblick über AutoSupport. 
---
= Was ist AutoSupport
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
AutoSupport ist ein Telemetriemechanismus, der den Zustand Ihres Systems proaktiv überwacht und Konfigurations-, Status-, Performance- und Systemereignisse automatisch an NetApp sendet.

Mithilfe dieser Daten beschleunigt der technische Support von NetApp die Diagnose und Behebung von Problemen. Zudem erkennt Digital Advisor potenzielle Probleme proaktiv und verhindert diese. Sie kann auch an interne Support-Abteilungen und Support-Partner gesendet werden.


NOTE: Digital Advisor zeigt AutoSupport-bezogene Daten nur für Systeme an, deren AutoSupport-Daten weniger als 60 Tage alt sind.

Bei ONTAP Systemen ist AutoSupport standardmäßig aktiviert, wenn Sie Ihr Storage-System zum ersten Mal konfigurieren. Sollten Sie link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/GUID-91C43742-E563-442E-8161-17D5C5DA8C19.html["AutoSupport einrichten"^] In ONTAP Systemen zu steuern, wie die AutoSupport Informationen an den technischen Support und Ihre interne Support-Abteilung gesendet werden.

Wenn Sie AutoSupport nicht aktivieren möchten, können Sie die Funktion zum Hochladen von AutoSupport verwenden, um AutoSupport Daten manuell hochzuladen. So erhalten Sie Empfehlungen und Einblicke in Ihr Storage-Ecosystem.


NOTE: AutoSupport-Daten enthalten keine Benutzerdaten.

Weitere Informationen zu AutoSupport finden Sie in der entsprechenden Dokumentation:

* link:https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["ONTAP (FAS UND AFF)"^]
* link:https://docs.netapp.com/us-en/storagegrid-117/admin/what-is-autosupport.html["StorageGRID"^]
* link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/autosupport-feature-overview.html["SANtricity (E-Series und EF-Series)"^]
* link:https://docs.netapp.com/us-en/solidfire-active-iq/concept-active-iq-learn-about-active-iq.html["Element (NetApp HCI und SolidFire)"^]
* link:https://www.netapp.com/pdf.html?item=/media/10438-tr-4444pdf.pdf["Technischer Bericht: ONTAP AutoSupport and AutoSupport On Demand"^]
* link:https://www.netapp.com/pdf.html?item=/media/10439-tr4688pdf.pdf["Technischer Bericht: Sicherheit und Schutz von NetApp Telemetriedaten"^]

