---
sidebar: sidebar 
permalink: concept_get_started_with_health_check_dashboard.html 
keywords: activeiq, health check, health, hca, health check dashboard, autosupport, autosupport adoption, recommended configuration, best practices, support, support and entitlements, support contract, contracts, active contracts, expired contracts, nearing-expiration, key recommendations, recommendations, digital advisor, features, recommended software 
summary: Enthält Informationen zum Dashboard, zu Zustandscores, zu Funktionen und zu den Widgets. 
---
= Legen Sie los mit dem Digital Advisor Health Check-Dashboard
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dieses Dashboard bietet eine Übersicht über die installierte Basis über die folgenden Widgets:

* *AutoSupport Adoption*: Zeigt die Anzahl und den Prozentsatz der Systeme mit aktiviertem AutoSupport an. Es können auch Systeme mit dem Status „Declined“, solche mit aktiviertem *HTTPS* und *AutoSupport on Demand* sowie *Loss of Signal* für Systeme angezeigt werden, die in den letzten 7 Tagen keine AutoSupport Daten mehr gesendet haben. Zur Anzeige des Health-Check-Scores und der Informationen zu den Systemen in Ihrer Installationsbasis kann das *AutoSupport Adoption* Widget ausgewählt werden.
* * Empfohlene Konfiguration*: Zeigt Systeme an, die konform und nicht kompatibel sind, wie im Widget * Recommended Configuration* beschrieben. Es hilft Ihnen, Maßnahmen zu ergreifen, um sicherzustellen, dass Ihre Systeme an Ihrer gesamten installierten Basis gut konfiguriert sind. Sie können den auf dem Dashboard bereitgestellten Wert anzeigen und anhand der Empfehlungen, die nach Priorität angegeben wurden, Maßnahmen ergreifen.
* *Empfohlene Software*: Zeigt eine konsolidierte Liste aller Software- und Firmware-Upgrades und Währungsempfehlungen an. Sie können sich die Systeme mit aktivierter AutoSupport anzeigen lassen, die entweder die Mindestversion oder die neueste Software oder die neueste Firmware aufweisen sollten.
* *Support & Entitlements*: Zeigt Supportverträge an, die abgelaufen sind, sowie solche, die in den nächsten 6 bis 12 Monaten ablaufen. Es werden Plattformen, Datenträger, Gehäuse mit Supportende, die Einhaltung von Entitlements, bevorstehende Abläufe sowie Fälle angezeigt, in denen das Supportende für Plattform und Hardware nicht zutrifft. Auf dem Dashboard ist der Health-Check-Score ersichtlich, und es können Maßnahmen auf Basis der wichtigsten, nach Priorität geordneten Empfehlungen ergriffen werden. Detaillierte Informationen zu Supportverträgen sind über das Widget *Support & Entitlements* verfügbar. Mit diesem Widget ist auch die Verlängerung von Supportverträgen möglich.
* *Best Practices*: Zeigt die Bewertung der Systemüberprüfung an, indem Sie die Best Practices-Attribute Ihres Storage-Systems bewerten: Schwachstellen bei Performance und Effizienz, Verfügbarkeit und Schutz, Kapazität, Konfiguration und Sicherheit. Die NetApp Best Practices tragen dazu bei, den Systemzustand zu erhalten, wodurch die Performance Ihrer installierten Basis optimiert wird.
* *Technische Cases*: Bietet Ihnen einen detaillierten Überblick über Ihre technischen Fallhistorie, nach Falltyp und offenem oder geschlossenem Status über wählbare Zeitbereiche.  Sie können sich detaillierte Fallgruppen ansehen sowie Einzelheiten zu den Support-Fällen über anzeigen lassen link:https://mysupport.netapp.com//["NetApp Support Website"^] Oder anderen Case-Portalen.

