---
sidebar: sidebar 
permalink: concept_understand_health_check_dashboard.html 
keywords: activeiq, health check, health, HCA, health check dashboard, health check score 
summary: Enthält Informationen, die Sie mit dem Health Check Dashboard vertraut machen können. 
---
= Verstehen Des Health Check Dashboard
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Das Digital Advisor Health Check Dashboard ermöglicht eine zeitpunktgenaue Überprüfung Ihrer gesamten Umgebung.

Auf der Grundlage des Ergebnis der Systemüberprüfung können Sie Ihre Storage-Systeme an den empfohlenen NetApp Best Practices ausrichten, um die langfristige Planung zu ermöglichen. Es hilft Ihnen, alle Systeme, die auf Software und Hardware ausgeführt werden, über eine zentrale Benutzeroberfläche zu überwachen. Ergebnisse der Integritätsprüfung ermöglichen Ihnen schnelle Einblicke in Systemrisiken. Mit den wichtigsten Empfehlungen und Best Practices können Sie Maßnahmen zur Verbesserung des Zustands Ihrer installierten Basis ergreifen.


NOTE: Sie können nur über die Serviceangebote von NetApp SupportEdge Advisor und SupportEdge Expert auf das Dashboard zur Zustandsprüfung zugreifen.
