---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: Enthält Informationen zum Dashboard, zu Watchlisten, zu Funktionen und zu den Widgets. 
---
= Lernen Sie die Funktionen von Digital Advisor kennen
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Mit Digital Advisor können Sie den Gesamtstatus Ihres Storage-Systems, allgemeine Informationen zum Systemzustand, Inventar, Planung, Upgrades und wertvolle Einblicke auf Uhrlistenebene anzeigen.

Wenn Sie zum ersten Mal auf Digital Advisor zugreifen, können Sie entweder eine Watchlist erstellen oder nach Kundennamen, Standortnamen, Gruppennamen, StorageGRID, Hostnamen suchen. Cluster, Seriennummer oder System-ID.

Sie sollten auch die Farben kennen, die auf die Karten angewendet werden, die den Schweregrad und die Art der Risiken angeben.

Im Folgenden sind einige Funktionen von Digital Advisor aufgeführt:

* Anzeigen mehrerer Watchlisten, nützlicher und nützlicher Informationen auf einen Blick.
* Sie erhalten Einblick in alle Risiken für Ihr Storage-System und die Maßnahmen zur Risikominderung.
* Risiken mit Active IQ Unified Manager verringern
* Aktualisieren Sie Ihr Storage-System.
* Sehen Sie sich den Nachhaltigkeitswert und den prognostizierten Stromverbrauch, direkten Kohlenstoff und die Wärmeabgabe an. Ausgehend von der Nachhaltigkeitsscore beurteilen Sie die allgemeine Effizienz Ihrer Storage-Systeme und passen sie an die empfohlenen Maßnahmen von NetApp zur Verbesserung des erzielten Ergebnisses an. link:concept_understand_sustainability_dashboard.html["Weitere Informationen ."].
* Anzeige des Datenreduzierungsverhältnisses, des genutzten logischen Speicherplatzes, des genutzten physischen Speicherplatzes und der insgesamt gespeicherten Daten für Storage-Systeme mit ONTAP 9.1 und höher
* Analysieren Sie die Performance Ihrer Speichergeräte anhand des grafischen Formats der Performance-Daten.
* Informieren Sie sich über Hardware und Software, die abgelaufen sind oder innerhalb der nächsten 6 Monate kurz vor dem Ablaufdatum stehen.
* Aktualisieren Sie Ihre ONTAP-Firmware mit Ansible.
* Informieren Sie sich über Systeme, die eine Kapazität von mehr als 90 % oder fast 90 % erreicht haben.
* Zeigen Sie detaillierte physische und logische Konfigurationsinformationen an, einschließlich einer Zusammenfassung der Cluster- und Node-Konfiguration, Informationen zu lokalen Ebenen und Volumes, Informationen zu Netzwerkschnittstelle und Port, einem Stack-Diagramm mit Details zu den Festplatten und Shelfs sowie einigen Kabelvisualisierungen.
* Stack-übergreifende Informationen und Erkenntnisse bereitstellen, die für Fehlerbehebung, Upgrade-Bewertungen, Lösungsvalidierung und Migration von Nutzen sind
* Prüfen Sie die Kompatibilität der Hosts, und geben Sie Upgrade-Empfehlungen für Host-Betriebssysteme, Treiber und .
* Finden Sie genau das, was Sie auf intelligente und schnellere Weise finden möchten.



NOTE: Sie können das Supportangebot über das Widget *Configuration* auf dem System-Dashboard aktualisieren, um Einblicke in Ihre Installationsbasis zu erhalten und personalisierte Unterstützung zu erhalten.
