---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor (ehemals Active IQ Digital Advisor) ist nun vollständig in BlueXP integriert. Sie können jetzt Ihre Cluster verwalten und auf alle Funktionen von Digital Advisor über die Benutzeroberfläche von BlueXP zugreifen.' 
---
= Integration von Digital Advisor in BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor (ehemals Active IQ Digital Advisor) ist nun vollständig in BlueXP integriert. Sie können jetzt Ihre Cluster verwalten und auf alle Funktionen von Digital Advisor über die Benutzeroberfläche von BlueXP zugreifen.

Mithilfe von BlueXP können IT-Experten und Cloud-Architekten ihre hybride Multi-Cloud-Infrastruktur zentral managen. Sie benötigen lediglich ein NSS-Konto (NetApp Support Site), um auf Digital Advisor in BlueXP zuzugreifen.



== Überblick über die Integration

Ab November 2022 wird Digital Advisor Benutzern empfohlen, Digital Advisor in BlueXP zu verwenden. Von BlueXP haben Sie Zugriff auf dieselbe Digital Advisor-Oberfläche, die Sie gewohnt sind, und mehr. Mit BlueXP können Sie Cloud-Storage erstellen und verwalten (z. B. Cloud Volumes ONTAP), Datenservices von NetApp (z. B. Cloud-Backup) sowie viele lokale und Edge-Storage-Geräte steuern.



== Greifen Sie auf den Digital Advisor in BlueXP zu

Sie können über BlueXP auf Digital Advisor zugreifen, um den Cluster zu verwalten.

.Schritte
. Öffnen Sie einen Webbrowser, und gehen Sie zu https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^]
. Wählen Sie *Melden Sie sich mit Ihren Anmeldedaten für die NetApp Support Website* an, und geben Sie Ihre Zugangsdaten ein.
+
Wenn Sie zuvor einen BlueXP-Login mit einer E-Mail und einem Passwort erstellt haben, müssen Sie diese Login-Option stattdessen weiter verwenden.

. Melden Sie sich bei der entsprechenden Aufforderung mit Ihren Anmeldedaten für die NetApp Support Site an.
+
Diese Anmeldung unterscheidet sich von der Anmeldung in Schritt 2. In Schritt 2 haben Sie sich bei der BlueXP-Plattform angemeldet. Jetzt melden Sie sich bei Digital Advisor an.



*Ergebnis*

Alle Ihre bestehenden Watchlisten und Konfigurationen werden angezeigt, und Sie können Digital Advisor jetzt verwenden, wie Sie es normalerweise tun.



== Erfahren Sie mehr über BlueXP

https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["Weitere Informationen finden Sie in der Dokumentation zu BlueXP"^]
