---
sidebar: sidebar 
permalink: learn_BlueXP_sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP 
summary: Bietet Informationen zur Nachhaltigkeit, mit deren Hilfe Sie den Energieverbrauch senken und Ihre Umweltziele erreichen können. 
---
= Erfahren Sie mehr über Nachhaltigkeit
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachhaltigkeit als Service ermöglicht es Ihnen, den Energieverbrauch zu senken und Ihre Umweltziele zu erreichen. So passen Sie Ihre Storage-Systeme an umweltfreundliche Praktiken an und erreichen Ihre Nachhaltigkeitsziele.

Über das Dashboard „Nachhaltigkeit“ können Sie die Nachhaltigkeitsbewertung und die prognostizierte Nutzung von Strom, direktem Kohlenstoff und Wärme aus dem Dashboard „Nachhaltigkeit“ anzeigen. Sie können den Prozentsatz der CO2-Minderung für bestimmte Standorte anpassen. Sie können die Nachhaltigkeitsbewertung auch auf Cluster-Ebene anzeigen. Auf der Grundlage der Nachhaltigkeitsbewertung können Sie die Nachhaltigkeit bewerten und die empfohlenen Maßnahmen von NetApp implementieren, um die Punktzahl zu verbessern. Weitere Informationen zum Dashboard Nachhaltigkeit finden Sie unter link:BlueXP_sustainability_dashboard_overview.html["Übersicht über das Dashboard „Nachhaltigkeit“"].


NOTE: Nachhaltigkeit wird auf AFF Systemen unterstützt – sowohl Der A-Serie als auch der C-Serie, FAS Systemen und Cloud Volumes ONTAP (CVO).

Sie können das folgende Video ansehen, um mehr über das Dashboard „Nachhaltigkeit“ zu erfahren:

video::yNRHeOvbGX8[youtube,width=848,height=480]


== Vorteile von Nachhaltigkeit

Nachhaltigkeit bietet folgende Vorteile:

* Steigerung der Performance durch Reduzierung der Anzahl an Storage-Geräten, die die gleiche Datenmenge speichern sollen
* Senken Sie Storage-Kosten durch Optimierung der Auslastung der Storage-Systeme.
* Verringern Sie den CO2-Ausstoß durch den Einsatz erneuerbarer Energien in Datacentern.
* Verbesserung der Energieeffizienz durch die Umsetzung energieeffizienter Maßnahmen.

