---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP, NetApp Console 
summary: Bietet Informationen zur Nachhaltigkeit, mit deren Hilfe Sie den Energieverbrauch senken und Ihre Umweltziele erreichen können. 
---
= Erfahren Sie mehr über Nachhaltigkeit
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durch Nachhaltigkeit können Sie den Energieverbrauch senken und auf Ihre Umweltziele hinarbeiten.  So können Sie Ihre Speichersysteme umweltfreundlich ausrichten und die Nachhaltigkeitsziele erreichen.

Sie können den Nachhaltigkeitswert und den prognostizierten Verbrauch von Strom, direktem Kohlenstoff und Wärme im Nachhaltigkeits-Dashboard anzeigen.  Sie können den Prozentsatz der CO2-Minderung für bestimmte Standorte anpassen.  Sie können den Nachhaltigkeits-Score auch auf Clusterebene anzeigen.  Anhand des Nachhaltigkeits-Scores können Sie die Nachhaltigkeitsposition beurteilen und die von NetApp empfohlenen Maßnahmen zur Verbesserung des Scores umsetzen.  Weitere Informationen zum Nachhaltigkeits-Dashboard finden Sie unterlink:sustainability-dashboard-overview.html["Übersicht über das Dashboard „Nachhaltigkeit“"] .


NOTE: Nachhaltigkeit wird auf Cloud Volumes ONTAP, AFF Systemen (A-Series und C-Series), E-Series, FAS und StorageGRID Systemen unterstützt.

Sie können das folgende Video ansehen, um mehr über das Dashboard „Nachhaltigkeit“ zu erfahren:

video::yNRHeOvbGX8[youtube,width=848,height=480]


== Vorteile von Nachhaltigkeit

Nachhaltigkeit bietet folgende Vorteile:

* Steigerung der Performance durch Reduzierung der Anzahl an Storage-Geräten, die die gleiche Datenmenge speichern sollen
* Senken Sie Storage-Kosten durch Optimierung der Auslastung der Storage-Systeme.
* Verringern Sie den CO2-Ausstoß durch den Einsatz erneuerbarer Energien in Datacentern.
* Verbesserung der Energieeffizienz durch die Umsetzung energieeffizienter Maßnahmen.

