---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, benefits, ontap, netapp console 
summary: Bietet Informationen zur Nachhaltigkeit, mit deren Hilfe Sie den Energieverbrauch senken und Ihre Umweltziele erreichen können. 
---
= Erfahren Sie mehr über Nachhaltigkeit mit Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durch Nachhaltigkeit können Sie den Energieverbrauch senken und auf Ihre Umweltziele hinarbeiten.  So können Sie Ihre Speichersysteme umweltfreundlich ausrichten und die Nachhaltigkeitsziele erreichen.

Im Sustainability-Dashboard können Sie den Nachhaltigkeitswert sowie den prognostizierten Verbrauch von Strom, direkten CO₂-Emissionen und Wärme einsehen. Der CO₂-Minderungsprozentsatz kann für bestimmte Standorte angepasst werden. Der Nachhaltigkeitswert ist auch auf Clusterebene einsehbar. Auf Basis des Nachhaltigkeitswerts lässt sich die Nachhaltigkeitslage beurteilen und die von NetApp empfohlenen Maßnahmen zur Verbesserung des Wertes umsetzen. Weitere Informationen zum Sustainability-Dashboard sind unter link:sustainability-dashboard-overview.html["Übersicht über das Dashboard „Nachhaltigkeit“"] verfügbar.


NOTE: Nachhaltigkeit wird auf Cloud Volumes ONTAP, AFF Systemen (A-Series und C-Series), E-Series, FAS und StorageGRID Systemen unterstützt.

Sie können das folgende Video ansehen, um mehr über das Dashboard „Nachhaltigkeit“ zu erfahren:

video::yNRHeOvbGX8[youtube,width=848,height=480]


[[benefits-of-sustainability]]
== Vorteile von Nachhaltigkeit

Nachhaltigkeit bietet folgende Vorteile:

* Steigerung der Performance durch Reduzierung der Anzahl an Storage-Geräten, die die gleiche Datenmenge speichern sollen
* Senken Sie Storage-Kosten durch Optimierung der Auslastung der Storage-Systeme.
* Verringern Sie den CO2-Ausstoß durch den Einsatz erneuerbarer Energien in Datacentern.
* Verbesserung der Energieeffizienz durch die Umsetzung energieeffizienter Maßnahmen.

