---
sidebar: sidebar 
permalink: reference_aiq_faq.html 
keywords: faq, frequently asked questions, non-technical, non-technical case, inventory, storage efficiency, capacity, performance 
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen für Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden Fragen beantworten Ihre häufigen Fragen zu Digital Advisor.



[[technical-case]]
== Technische Fallstudie

*Wann erstelle ich einen technischen Case?*

Technische Cases sollen bei technischen Problemen im Zusammenhang mit Hardwareunterbrechungen, schlechter Performance, Datenproblemen oder Anforderungen an technische Informationen Unterstützung bei jedem der NetApp Produkte erhalten.

*Wie erstelle ich einen technischen Case?*

. link:https://mysupport.netapp.com/site/global/dashboard["Hier"^] öffnet die NetApp Support-Website.
. Im oberen Menü die Option *Meine Fälle* auswählen.
. *Fall erstellen* auswählen.
. Eine Kategorie auswählen, die erforderlichen Details angeben und *Neue Suche* auswählen, um in Ihrem Bestand nach einem System zu suchen.
. Wählen Sie aus der angezeigten Liste das System aus, um den Fall zu erstellen.
. Wählen Sie die Priorität für den neuen Fall aus.
. Wählen Sie die entsprechende Kategorie aus der Dropdown-Liste *Problemkategorie* aus.
. Die Problembeschreibung wird in das Feld „Problembeschreibung“ eingegeben und *Weiter* wird ausgewählt.
. Geben Sie weitere Details über das Problem an.
. *Dateien auswählen* auswählen, um Dateien oder Bilder hochzuladen, die bei der Diagnose des Problems helfen können.
. Wählen Sie *Fortfahren*.
. Geben Sie Ihre Kontaktdaten an.
. *Fall erstellen* auswählen.




[[non-technical-case]]
== Nicht-technische Support-Cases

*Was ist ein nicht-technischer Fall?*

Probleme wie unfähige Systeme im Bestand, falsche Vertragstermine usw., die nicht technisch sind, werden als nichttechnische Fälle klassifiziert.

*Wann erstelle ich einen nicht-technischen Case?*

Es sollte ein nicht-technischer Case für die folgenden Fälle erstellt werden:

* Auf bestimmte Funktionen kann nicht zugegriffen werden, oder Sie benötigen Unterstützung bei Digital Advisor-Funktionen
* Fehlende Systeme im Bestand
* Außerbetriebnahme eines Systems von der Installationsbasis
* Falsche oder fehlende Vertragslaufzeit
* Inkorrektes Support-Angebot


*Wie erstelle ich einen nicht-technischen Fall?*

. Wählen Sie link:https://mysupport.netapp.com/site/help["Hier"^], um das „Tool für nicht-technisches Feedback“ auf der NetApp Support-Website zu öffnen.
. Wählen Sie die entsprechende Kategorie aus der Dropdown-Liste *Feedbackkategorie* aus.
. Geben Sie die erforderlichen Angaben ein und geben Sie zusätzliche Informationen in das Feld „Kommentare“ ein.
. Wählen Sie *Absenden*.


Es wird ein Case erstellt und Ihnen wird eine Case-Nummer zur Verfügung gestellt.

*Wie kann ich Feedback geben oder andere Fragen im Zusammenhang mit Digital Advisor stellen?*

Um Feedback zu geben oder Fragen zu stellen, senden Sie eine E-Mail an mailto:ng-activeiq-feedback@netapp.com[.underline]#ng-activeiq-feedback@netapp.com#].



[[storage-efficiency]]
== Storage-Effizienz

*Wie erhalte ich Zugriff auf Storage Efficiency in Digital Advisor?*

. Öffnen Sie die Homepage von link:https://activeiq.netapp.com/?source=onlinedocs["Digital Advisor"^].
. Über das Suchfeld oben rechts nach Kunden, Standorten, Gruppen, Clustern oder Nodes suchen, um das entsprechende Dashboard zu erreichen.
. *Speichereffizienz* im linken Navigationsbereich auswählen.



NOTE: Die mit einer Watchlist erstellten Dashboards werden im Widget „Storage-Effizienz“ nicht angezeigt.

*Zeigt Digital Advisor Verhältnisse für alle ONTAP Systeme an?*

Ja, Digital Advisor zeigt die Verhältnisse für alle ONTAP Systeme an.

Was bewirkt die Option „Mit Snapshot-Kopien“ im Effizienz-Dashboard?

Das Digital Advisor Efficiency Dashboard berechnet das Datenreduktionsverhältnis auf mehreren Ebenen, einschließlich Kunde, Standort, Gruppe, Cluster und Knoten. Wird der Schalter *Mit Snapshot-Kopien* eingeschaltet, umfasst die Berechnung des Datenreduktionsverhältnisses die folgenden Speichereffizienztechnologien:

* Deduplizierung
* Komprimierung
* Data-Compaction
* Klone
* Snapshots


Standardmäßig wird bei der Berechnung des Datenreduktionsverhältnisses die Snapshot-Speichereffizienztechnologie nicht berücksichtigt.

*Was werden physische Daten verwendet und logische Daten verwendet?*

* Physische Blöcke Verbraucht/Physische Daten Genutzt
+
** Der Speicherplatz, der aktuell für Daten verwendet wird (und nicht für zukünftige Verwendung reserviert),
** Beinhaltet den von Aggregat-Snapshot-Kopien belegten Speicherplatz
** Der tatsächlich vom Client verbrauchte/geschriebene Speicherplatz


* Insgesamt Verwendete Logische Daten
+
** Zeigt die im Aggregat verwendete logische Größe an.
** Dies umfasst Volumes, Klone und Snapshots im Aggregat.
** Die logische Größe wird basierend auf der physischen Nutzung (echter Schreibvorgänge) und den im Aggregat erzielten Einsparungen berechnet.
** Enthält keinen Speicherplatz, der für zukünftige Verwendung reserviert ist




*Welche AutoSupport-Instanzen werden zur Berechnung des Datenreduzierungsverhältnisses verwendet?*

Die Berechnungen werden entweder mit den letzten wöchentlichen oder benutzergetriggerten AutoSupport-Instanzen durchgeführt, die in der Regel die meisten Abschnitte enthalten, die für die Berechnung des Verhältnisses erforderlich sind.

*Welche Volumes oder Aggregate sind von der Berechnung der Datenreduzierung ausgeschlossen?*

Die folgenden Objekte werden bei der Berechnung des Datenreduzierungsverhältnisses nicht berücksichtigt:

* Root-Aggregate
* Offline-Volumes
* Root-/Admin-Root-Volumes von Vserver
* MCC Konfigurations-Volumes


*Wie sehe ich den Trend in der Datenreduktionsrate?*

Derzeit wird das Datenreduzierungsverhältnis auf der Grundlage der letzten wöchentlichen bzw. vom Benutzer ausgelösten AutoSupport-Instanz berechnet. Die Trendanalyse kann für eine zukünftige Version in Betracht gezogen werden.

*Wie werden Verhältnisse auf Kundenebene und Einsparungen bei der Datenreduzierung berechnet?*

Das Dashboard zur Speichereffizienz auf Kundenebene zeigt das Datenreduktionsverhältnis mit und ohne Snapshot-Kopien für AFF und Nicht-AFF-Systeme an und kombiniert die Daten über die installierte Basis des Kunden. Die für die folgenden Berechnungen erforderlichen Parameter stammen aus ONTAP AutoSupport:

Ohne Snapshot-Kopien (zuerst pro Aggregat berechnet):

|===
| *Betrieb* | *Formel* 


| Aggr Logical verwendet ohne Snapshot-Kopien | Logische Größe, die von Volumes, Klonen und Snapshot-Kopien im Aggregat verwendet wird, abzüglich der logischen Größe, die von Snapshot-Kopien verwendet wird 


| Aggr Physisch verwendet ohne Snapshot-Kopien | Gesamter physischer Speicherplatz – (Physischer Speicherplatz, der von Snapshot-Kopien belegt wird / Aggregierte Datenreduktionsrate) 


| Kundeneffizienzverhältnis ohne Snapshot Kopien | Summe [Aggr Logical Used ohne Snapshot-Kopien für alle Aggregate und für alle Knoten eines Kunden] / Summe [Aggr Physical Used ohne Snapshot-Kopien für alle Aggregate und für alle Knoten eines Kunden] : 1 
|===
Mit Snapshot-Kopien:

|===
| *Betrieb* | *Formel* 


| Kundenlogische Größe mit Snapshot-Kopien | Summe [Logische Größe, die von Volumes, Klonen und Snapshot-Kopien für alle Aggregate und für alle Knoten eines Kunden verwendet wird] 


| Physische Kundengröße, verwendet mit Snapshot-Kopien | Summe [physische Gesamtgröße verwendet für alle Aggregate und alle Nodes eines Kunden] 


| Kundeneffizienzverhältnis mit Snapshot Kopien | Logische Kundengröße mit Snapshot-Kopien und Klonen / Physische Kundengröße mit Snapshot-Kopien und Klonen: 1 
|===
Berechnungen der Tabellen für Effizienzfunktionen:

|===
| *Betrieb* | *Formel* 


| Physikalischer Speicherplatz Des Kunden | Summe des physischen Speicherplatzes, der vom Aggregat für alle Aggregate und aller Nodes eines Kunden verwendet wird 


| Vom Kunden verwendete logische Größe ohne Snapshot-Kopien | Summe des von Volumes, Klonen und Snapshot-Kopien belegten logischen Speicherplatzes, abzüglich des von Snapshot-Kopien belegten logischen Speicherplatzes für alle Aggregate aller Knoten eines Kunden 


| Vom Kunden genutzte logische Größe mit Snapshot-Kopien | Summe des von Volumes, Klonen und Snapshot-Kopien im Aggregat belegten logischen Speicherplatzes für alle Aggregate aller Knoten eines Kunden 


| Insgesamt Eingesparter Speicherplatz | Insgesamt Genutzter Logischer Speicherplatz – Physischer Speicherplatz 


| Einsparungen Durch Deduplizierung | Summe des durch Volume-Deduplizierung eingesparten Speicherplatzes + durch Inline-Zero-Mustererkennung jedes Aggregats aller Nodes eines Kunden eingesparte Speicherplatzes 


| Einsparungen Durch Komprimierung | Summe des durch Volume-Komprimierung eingesparten Speicherplatzes für alle Nodes eines Kunden 


| Einsparungen durch Data-Compaction (für ONTAP 9.1) | Summe des durch die aggregierte Data-Compaction in jedem Aggregat aller Nodes eines Kunden eingesparten Speicherplatzes 


| Einsparungen durch Data-Compaction (für ONTAP 9.2 und höher) | Summe des durch aggregierte Datenreduzierung in jedem Aggregat aller Nodes eines Kunden eingesparten Speicherplatzes 


| FlexClone Einsparungen | Summe (logische Größe wird von FlexClone Volumes verwendet – von FlexClone Volumes genutzte physische Größe) jedes Aggregats aller Nodes eines Kunden 


| Einsparungen bei Backups mit Snapshot Kopien | Summe aus (Logischer Größe der von Snapshot-Kopien verwendeten Größe - Physischer Größe der von Snapshot-Kopien verwendeten Größe) aller Aggregate aller Knoten eines Kunden 
|===
*Warum ergeben sich bei jeder einzelnen Datenreduzierung nicht Einsparungen durch Datenreduzierung?*

Die Einsparungen durch Datenreduzierung werden im Storage-Effizienz-Dashboard für Volumes und lokale Tiers (Aggregate) dargestellt.  Sie können Volume-Einsparungen und Aggregat-Einsparungen nicht hinzufügen, da beide an unterschiedlichen Storage-Objekten geschehen.

*Warum wurde die Datenreduzierung vor dem Upgrade auf ONTAP als höher oder falsch gemeldet?*

Wenn aufgrund eines Fehlers in ONTAP Datensicherungs-Volumes im Node vorhanden sind, wird die Datenreduzierung höher angezeigt. Das Problem wurde in ONTAP 9.3P11 behoben. Bei einem Upgrade von ONTAP Versionen vor 9.3P11 sowie bei Datensicherungs-Volumes im Node werden korrekte oder niedrigere Werte angezeigt.



[[inventory]]
== Inventar

*Warum kann ich bestimmte Systeme in Digital Advisor nicht finden?*
Möglicherweise können Sie aus einem der folgenden Gründe nicht nach bestimmten Systemen suchen oder diese auf der Bestandsseite anzeigen:

* Neue Systeme dauern einen Tag, bis sie in Digital Advisor reflektiert werden, sobald sie in SAP hinzugefügt oder aktualisiert wurden.
* Die Systeme sind sicher und Sie sind nicht berechtigt, die sicheren Systeme anzuzeigen.
* Sie sind nicht berechtigt, die Systeme anzuzeigen.
* Systeme werden in SAP inaktiv, archiviert oder stillgelegt.


Falls Sie aus anderen Gründen keine Systeme anzeigen können, Fragen haben oder Zugriff beantragen möchten, link:https://mysupport.netapp.com/site/help["Erstellen eines nicht-technischen Case"^]. Weitere Informationen zu nicht-technischen Fällen sind verfügbar unter <<Nicht-technische Support-Cases,Hier.>>



[[capacity]]
== Kapazität

*Wie werden Kapazitäten in Digital Advisor berechnet?* Die Kapazitäten in Digital Advisor werden für Cluster und Knoten berechnet, wobei Root ausgeschlossen und Snapshot-Kopien eingeschlossen sind.

|===
| * Kapazität* | *Berechnet durch Hinzufügen jedes Aggregats…* 


| Bruttokapazität | Alle Phys (MB/blks) von „SYSCONFIG -R“ 


| Nutzbare Kapazität | Kbytes (zugewiesen) von „DF -A“ 


| Genutzte Kapazität (mit Reserve) | Verwendung von „DF -A“ 


| Verfügbare Kapazität | Verfügbar von „DF -A“ 


| Physische Kapazität (Tatsächlich) | Gesamte physikalische Nutzung von „AGGR-EFFICIENCY.XML“ 


| Logische Kapazität (Effektiv) | Logische Größe, die von Volumes, Klonen und Snapshot-Kopien im Aggregat von "AGGR-EFFICIENCY.XML" verwendet wird 
|===
*Für die lokale Ebene (Aggregate mit Snapshot-Kopien)*

|===
| * Kapazität* | *Berechnet mit…* 


| Nutzbare Kapazität | Kbytes (zugewiesen) von „DF -A“ 


| Genutzte Kapazität (mit Reserve) | Verwendung von „DF -A“ 


| Verfügbare Kapazität | Verfügbar von „DF -A“ 


| Physische Kapazität (Tatsächlich) | Gesamte physikalische Nutzung von „AGGR-EFFICIENCY.XML“ 


| Logische Kapazität (Effektiv) | Logische Größe, die von Volumes, Klonen und Snapshot-Kopien im Aggregat von "AGGR-EFFICIENCY.XML" verwendet wird 
|===
*Für Volume (Volume mit Snapshot-Kopien)*

|===


| * Kapazität* | *Berechnet mit…* 


| Volume-Kapazität | Volume-Größe von „VOLUME.XML“ 


| Genutzte Kapazität (mit Reserve) | Verwendete Größe von „VOLUME.XML“ 


| Verfügbare Kapazität | Verfügbare Größe „VOLUME.XML“ 


| Physische Kapazität (Tatsächlich) | Gesamtzahl der von „Vol STATUS -S“ verwendeten physischen 


| Logische Kapazität (Effektiv) | Logische verwendete Größe von „VOLUME.XML“ 
|===
*Was sind physische Kapazität (tatsächlich), logische Kapazität (effektiv) und genutzte Kapazität (mit Reserve)?*

* Verbrauchte Physische Blöcke/Genutzte Physische Kapazität (Tatsächlich)
+
** Der Speicherplatz, der aktuell für Daten verwendet wird (und nicht für zukünftige Verwendung reserviert),
** Beinhaltet den von Aggregat-Snapshot-Kopien belegten Speicherplatz
** Der tatsächlich vom Client benötigte Speicherplatz oder geschriebene Speicherplatz


* Genutzte Logische Kapazität (Effektive) Logische Daten
+
** Zeigt die im Aggregat verwendete logische Größe an
** Das Aggregat umfasst Volumes, Klone und Snapshot-Kopien.
** Die logische Größe wird basierend auf der physischen Nutzung (echter Schreibvorgänge) und den im Aggregat erzielten Einsparungen berechnet.





NOTE: Er enthält keinen Speicherplatz, der für zukünftige Verwendung reserviert ist.

* Genutzte/genutzte Gesamtkapazität (mit Reserve)
+
** Die Summe des gesamten Speicherplatzes, der im Aggregat von Volumes, Metadaten oder Snapshot-Kopien belegt oder reserviert wird





NOTE: Sie beinhaltet Speicherplatz, der für Volumes reserviert ist, die sich aus Datei- oder Volume-Garantietypen befinden. Dazu gehören Delayed Frees, aggr Blog und Metadaten zusätzlich zu den Reserven. Es wird als genutzter Speicherplatz angezeigt, bis die verzögerten freien Blöcke gelöscht werden. Nach dem Säugen verringert sich der verwendete Speicherplatz.

*Wie wird die Kapazitätsprognose berechnet?* die Kapazitätsprognose verwendet die im letzten Jahr verwendeten Kapazitätsdaten, um die durchschnittliche wöchentliche Wachstumsrate eines Systems zu berechnen. Diese Änderungsrate für die Systemnutzung wird dann auf die aktuelle genutzte Kapazität extrapoliert, um zu zeigen, wie sich die Systemauslastung in den nächsten 6 Monaten voraussichtlich ändern wird (vorausgesetzt, die nutzbare Gesamtkapazität bleibt unverändert).

*Warum stimmt die hinzugefügte belegte Kapazität jedes Volumes nicht mit der aggregierten belegten Kapazität auf Knotenebene überein?* Die belegte Kapazität auf Knotenebene umfasst den von Volumes reservierten Speicherplatz, Metadaten und Snapshot-Kopien. Sie umfasst außerdem den für Volumes reservierten Speicherplatz (Datei- oder Volume-Garantie-Typ). Daher stimmen die beiden Werte möglicherweise nicht überein.

*Werden Kapazitäten in Digital Advisor Base 2 oder Base 10 angezeigt?* Alle Kapazitäten im Digital Advisor werden als Base 2 (dividieren Sie sich durch 1024) angezeigt und stellen Kapazitäten in gib/tib dar. Der ONTAP Storage und andere NetApp Produkte zeigen zudem in Base 2 die Kapazitätsauslastung an.

Bei StorageGRID werden die Kapazitäten in Basis 10 angezeigt und die Kapazitätseinheit wird in TB angegeben.



[[miscellaneous]]
== Verschiedenes

*Warum sind die Funktionen unter SPEICHERZUSTAND im linken Navigationsbereich deaktiviert?*
Die Verfügbarkeit der Funktionen unter *STORAGE HEALTH* hängt vom Systemtyp und -Level ab. ClusterViewer ist beispielsweise für ONTAP- und Cloud Volumes ONTAP-Systeme (CVO) auf Cluster- und Node-Ebene verfügbar. Sie können den Mauszeiger über das *i*-Symbol neben den einzelnen Funktionen bewegen, um mehr über die jeweiligen Systemtypen und -Ebenen zu erfahren.
