---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ONTAP systems, StorageGRID 
summary: Stellt Informationen zur Erhöhung der Kapazität des Systems bereit. 
---
= Identifizieren Sie Speichersysteme, die sich in Digital Advisor ihrer Kapazitätsgrenze nähern.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erkennen Sie proaktiv Systeme, die an ihre Kapazitätsgrenzen stoßen, und senden Sie eine Anfrage, die Kapazität Ihres Storage-Systems zu erhöhen.

ONTAP zeigt Systeme an, die in 1, 3 und 6 Monaten eine Kapazität von mehr als 90 % oder mehr als 90 % aufweisen. StorageGRID zeigt Systeme an, die in 1, 3 und 6 Monaten eine Kapazität von mehr als 70 % oder mehr als 70 % aufweisen.

.Schritte
. Klicken Sie im Widget *Planung* auf *Kapazitätserweiterungen*.
+
Standardmäßig werden die ONTAP-Systeme angezeigt, die eine Kapazität von 90 % überschritten haben oder fast 90 % erreicht haben.

. Klicken Sie auf die Registerkarte *StorageGRID*, um die StorageGRID-Systeme anzuzeigen, deren Kapazität 70 % überschritten hat oder fast 70 % beträgt.
. Wählen Sie die Systeme aus, für die Sie die Kapazität erhöhen möchten.
. Klicken Sie auf *View Capacity Forecast*, um die Kapazitätsprognose für die nächsten 6 Monate anzuzeigen.
. Klicken Sie auf *Anforderung zur Kapazitätserweiterung*.
. Geben Sie optional Kommentare ein.
. Klicken Sie auf *Senden*, um die Anfrage an das NetApp-Speicherteam zu senden, um die Kapazitätserweiterung für die ausgewählten Systeme zu unterstützen.

