---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Abonnieren Sie Benachrichtigungen zum Zustand Ihres Speichersystems von Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können den Wellness-Review-E-Mail-Service abonnieren, um monatlich eine E-Mail zu erhalten, die den Wellness-Status, Speichersysteme, deren Erneuerungsdatum näher rückt, und Speichersysteme, die ein Upgrade benötigen, für die NetApp Produkte in Ihrer installierten Basis zusammenfasst. Sie erhalten eine E-Mail mit einer monatlichen Zusammenfassung Ihres Speichersystems, in der Sie alle relevanten Informationen einsehen und gegebenenfalls Maßnahmen ergreifen können. Sie haben außerdem die Möglichkeit, Ihre Abonnements anzuzeigen, zu bearbeiten, zu teilen und zu löschen. Wenn Sie die E-Mail nicht mehr erhalten möchten, können Sie sich jederzeit vom E-Mail-Empfang abmelden.

Wenn das Abonnement aktiviert ist, sollten Sie beim Hinzufügen eines Abonnements ein Startdatum auswählen. Die monatliche E-Mail-Zusammenfassung bietet einen Überblick über ausstehende Maßnahmen in den Bereichen Wellness, Erneuerung, Upgrade und Health Check. Sie können die E-Mail-Adresse bestätigen und die E-Mail an die angegebene E-Mail-Adresse senden. Sie haben auch die Möglichkeit, Abonnements zu löschen.


NOTE: Diese Funktion ist nur über die Serviceangebote von NetApp SupportEdge Advisor und SupportEdge Expert verfügbar.

.Schritte
. Klicken Sie im linken Fensterbereich auf *Wellness-Übersicht*.
. Klicken Sie Auf *Abonnement Hinzufügen*.
. Geben Sie die erforderlichen Informationen in den Feldern *Name des Abonnements*, *Kategorie wählen*, *Kunden suchen* und *E-Mail* im Dialogfeld *Neues Abonnement hinzufügen* an.
. Klicken Sie Auf *Abonnieren*.
+
Nach erfolgreichem Abonnement erhalten Sie eine *Abonnement wurde hinzugefügt* Nachricht.


