---
sidebar: sidebar 
permalink: task_view_wellness_history.html 
keywords: wellness history, risks, wellness, view all actions, risk history, 
summary: Bietet Informationen zu Systemrisiken und zur Anzeige der Wellness-Geschichte. 
---
= Sehen Sie sich die Risikohistorie Ihres Speichersystems in Digital Advisor an.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die in den letzten drei Monaten aufgetretenen Risiken für Speichersysteme einsehen, um zu erfahren, wie sie sich im Laufe der Zeit entwickeln.

Diese Risiken werden unter vier Arten von Risiken klassifiziert – *ungelöst*, *neu*, *gelöst* und *anerkannt*. Sie werden durch verschiedene Farben dargestellt. Die Zusammenfassung dieser Risiken wird durch einen *Risikoverlauf*-Diagramm dargestellt.

.Schritte
. Klicken Sie im Dashboard im Fenster *Wellness* auf *Alle Aktionen anzeigen*.
. Klicken Sie Auf *Wellness-Geschichte*.
. Klicken Sie im Diagramm * Risikoverlauf* auf die Kategorie, für die Sie den Risikoverlauf anzeigen möchten.
+
Wenn Sie den Mauszeiger über die farbigen Balken bewegen, werden Informationen zur Anzahl der Risiken in jeder Kategorie angezeigt. Wenn Sie auf die jeweilige Risikokategorie klicken, werden die Informationen in der Tabelle *Risikoinformationen* angezeigt.

+
Sie können die Risikoübersicht auch in einem Excel-Arbeitsblatt herunterladen.


