---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: cloud insights, vms, virtual machines, data infrastructure insights 
summary: Bietet Informationen zu den virtuellen Maschinen in Data Infrastructure Insights 
---
= Nutzen Sie Digital Advisor , um die in Data Infrastructure Insights verfügbaren Daten zu virtuellen Maschinen anzuzeigen.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor ist jetzt in die Basisversion von Data Infrastructure Insights integriert, um Kunden eine vollständige Stapelinventur und Interoperabilitätsprüfungen bereitzustellen.

Vorteile dieser Integration:

* Vereinfachtes SaaS Monitoring von ONTAP
* Übersichtlichkeit des VMware Full-Stack-Monitoring
* Produktivitätseinsparungen für Kunden durch automatisierte Interoperabilitätsprüfungen zur Unterstützung der ONTAP-Upgrade-Planung. Dadurch werden ONTAP-Upgrades reibungsloser und die Risiken einer Inkompatibilität mit Hosts minimiert.



NOTE: Diese Funktion ist nur für Upgrade-Verträge mit SupportEdge Advisor, SupportEdge Expert und Digital Advisor verfügbar.

.Schritte
. Im Widget *Inventar* die Option *Virtuelle Maschinen* auswählen, um die in Data Infrastructure Insights verfügbaren Daten anzuzeigen.
. Die Registerkarte *Virtual Machine Overview* auswählen.
. Die *Anzahl der ESX-Hosts* zeigt Informationen über den Host an.
. Der *ESX Name* kann ausgewählt werden, um zu Data Infrastructure Insights zu navigieren und weitere Informationen anzuzeigen.

