---
sidebar: sidebar 
permalink: task_view_valuable_insight_widget.html 
keywords: valuable insight, support cases, storage efficiency savings, mitigated risks 
summary: Enthält Informationen zum Widget „wertvolle Einblicke“ 
---
= Mit dem Widget „Wertvolle Einblicke“ im Digital Advisor können Sie Supportfälle und Details zum Speichersystem einsehen.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Widget *wertvoller Insights* gibt Informationen zur Anzahl von Support-Cases, zu ausstehenden Software-Upgrades, zu Einsparungen durch Storage-Effizienz, zu entschärfenden Risiken und anderen. Außerdem werden die Risikobenachrichtigungen aus dem Attribut *Wellness* proaktiv aufgelistet.

video::QPJY2TWnRxQ[youtube,width=848,height=480]
.Schritte
. Klicken Sie im Widget *Inventory* auf *Systems*, um die Systeminformationen aller Plattformen anzuzeigen, oder klicken Sie auf den Plattformtyp und klicken Sie dann auf *Systems*, um die für diese Plattform spezifischen Systeme anzuzeigen.
. Klicken Sie auf den Node oder Cluster, um detaillierte Informationen über das System anzuzeigen.
+
Das Widget * Valuable Insights* ist auf dem Dashboard verfügbar.

. Lesen Sie die Informationen im Widget, um den geschäftlichen und technischen Mehrwert zu ermitteln, den Ihr Support-Vertrag erhalten hat.

