---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: Kapazitätsdetails und Einsparungen bei der Speichereffizienz für Ihr Speichersystem anzeigen. 
---
= Kapazitäts- und Speichereffizienzeinsparungen können Sie im Digital Advisor einsehen.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können sich die Kapazitätsdetails und die Einsparungen durch Storage-Effizienz in Ihrem System anzeigen lassen und entsprechende Maßnahmen ergreifen. Die Informationen zur Kapazität und Storage-Effizienz können entweder auf Cluster-Ebene oder auf Node-Ebene angezeigt werden.


NOTE: Diese Funktion wird auf Systemen der E-Series nicht unterstützt.

Das Kapazitäts-Dashboard zeigt die Kapazitätsdetails und die Kapazitätsprognose Ihres Systems an. Die Kapazitätsprognose nutzt historische Kapazitätsinformationen, um die Auslastung jedes Systems zu ermitteln. Basierend auf den historischen Daten (Daten eines Jahres, sofern verfügbar) der genutzten und zugewiesenen Kapazität berücksichtigt der Algorithmus die aktuelle Auslastung jedes Systems und erstellt eine Prognose für die Systemauslastung in den nächsten 1 bis 6 Monaten.

Das Dashboard zur Speichereffizienz zeigt das Datenreduktionsverhältnis, den belegten logischen Speicherplatz, den belegten physischen Speicherplatz und die insgesamt eingesparten Daten an. Das Datenreduktionsverhältnis und die Einsparungen sind mit und ohne Snapshot-Kopien für AFF Systeme, Nicht-AFF Systeme oder beide sichtbar. Die gesamten Dateneinsparungen im gesamten Kundenspeicher sind pro Effizienzfunktion wie Volume-Deduplizierung, Volume-Komprimierung, Kompaktierung, FlexClone Volumes und Snapshot-Kopien ersichtlich. Die fünf Speichersysteme mit dem besten Effizienzverhältnis können angezeigt werden. Die SAN- und NAS-Effizienz ohne Snapshot-Kopien ist auf Knotenebene für ONTAP Systeme einschließlich AFF A-Serie, AFF C190, All SAN Array und FAS500 ersichtlich.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Schritte
. Im linken Bereich ist *Kapazität und Effizienz* auszuwählen.
+
Standardmäßig ist die Registerkarte *Capacity* ausgewählt.

. Anzeigen der Kapazitätsinformationen auf Cluster- und Node-Ebene
+
.. Sehen Sie sich die Kapazitätsprognose auf Node-Ebene an.
+
Bei ONTAP-Systemen sind Informationen über ROHKAPAZITÄT in ClusterViewer verfügbar.



. *Kapazität hinzufügen* auswählen, um eine Benachrichtigung an NetApp oder Ihren Partner zu senden, damit Kapazität hinzugefügt wird.
. Anzeige der Storage-Effizienz und der Einsparungen Ihres Storage-Systems
+
.. Wenn das Speichereffizienzverhältnis Ihres Speichersystems höher als das durchschnittliche Speichereffizienzverhältnis ist, kann mit *Share Your Success Story* mitgeteilt werden, welche Best Practices angewendet wurden.
.. Wenn das Speichereffizienzverhältnis Ihres Speichersystems unter dem durchschnittlichen Speichereffizienzverhältnis liegt, wählen Sie *Contact Us*, um die Konfigurationen Ihres Speichersystems mitzuteilen.




Weitere Informationen über Kapazität und Storage-Effizienz finden Sie unter link:reference_aiq_faq.html["Häufig gestellte Fragen zu Digital Advisor"].
