---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ontap systems, storagegrid, storage expansion 
summary: Stellt Informationen zur Erhöhung der Kapazität des Systems bereit. 
---
= Identifizieren Sie Speichersysteme, die sich in Digital Advisor ihrer Kapazitätsgrenze nähern.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erkennen Sie proaktiv Systeme, die an ihre Kapazitätsgrenzen stoßen, und senden Sie eine Anfrage, die Kapazität Ihres Storage-Systems zu erhöhen.

ONTAP zeigt Systeme an, die in 1, 3 und 6 Monaten eine Kapazität von mehr als 90 % oder mehr als 90 % aufweisen. StorageGRID zeigt Systeme an, die in 1, 3 und 6 Monaten eine Kapazität von mehr als 70 % oder mehr als 70 % aufweisen.

.Schritte
. Im Widget *Planung* *Speichererweiterung* auswählen.
+
Standardmäßig werden die ONTAP-Systeme angezeigt, die eine Kapazität von 90 % überschritten haben oder fast 90 % erreicht haben.

. Die Registerkarte *StorageGRID* zeigt die StorageGRID Systeme an, deren Kapazität 70 % überschritten hat oder die sich 70 % Kapazität nähern.
. Wählen Sie die Systeme aus, für die Sie die Kapazität erhöhen möchten.
. *Kapazitätsprognose anzeigen* zeigt die Kapazitätsprognose für die nächsten 6 Monate an.
. *Kapazitätserweiterung anfordern* auswählen.
. Geben Sie optional Kommentare ein.
. *Senden* auswählen, um die Anfrage an das NetApp Speicherteam zu senden, damit Unterstützung bei der Speichererweiterung für die ausgewählten Systeme erfolgt.

