---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: Stellt Informationen zum Gesamtbestand bereit, zu dem Sie gehören. 
---
= Sehen Sie sich die Inventardetails Ihres Speichersystems in Digital Advisor an.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Widget *Inventar* bietet Ihnen eine Übersicht über alle Systeme und die Switches mit Supportberechtigung, die Sie besitzen.  Dies umfasst sowohl Digital Advisor -fähige als auch nicht-fähige Produkte.

Sie können auch den Bericht der ausgewählten Watchlist generieren und den Bericht an maximal 5 Empfänger senden.

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== Zeigen Sie Systemdetails an

.Schritte
. Im Widget *Inventar* *Systeme* auswählen, um die Systeminformationen aller Plattformen anzuzeigen, oder den Plattformtyp auswählen und dann *Systeme*, um Systeme anzuzeigen, die spezifisch für diese Plattform sind.
. Den Knoten oder Cluster auswählen, um detaillierte Informationen über das System anzuzeigen.
. *Herunterladen* auswählen, um den *Inventory*-Bericht herunterzuladen und die Systemdetails im .xls-Format anzuzeigen.
. *Herunterladen* auswählen, um den *Ansible Inventory* Bericht herunterzuladen und die Systemdetails im .yml- und .ini-Format auf Regions- oder Standortebene anzuzeigen.
+
Die Ansible-Bestandsdateien können mit benutzerdefinierten Ansible-Playbook-Dateien verwendet werden, um eine Änderung der Infrastrukturkonfiguration vorzunehmen.





[[view-support-entitled-switch-details]]
== Details zum Support-berechtigten Switch anzeigen

.Schritte
. Im Widget *Inventar* kann *Supportberechtigte Switches* ausgewählt werden, um Informationen zu allen supportberechtigten Switches anzuzeigen.

