---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines 
summary: Stellt Informationen zu den virtuellen Maschinen in Cloud Insights bereit 
---
= Integration in Cloud Insights zur Anzeige von Details zu Virtual Machines
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor ist jetzt in die Cloud Insights Basic-Version integriert, um Kunden einen vollständigen Stack-Bestand und Interoperabilitätsprüfungen zu bieten.

Vorteile dieser Integration:

* Vereinfachtes SaaS Monitoring von ONTAP
* Übersichtlichkeit des VMware Full-Stack-Monitoring
* Produktivitätseinsparungen für Kunden durch automatisierte Interoperabilitätsprüfungen zur Unterstützung der ONTAP-Upgrade-Planung. Dadurch werden ONTAP-Upgrades reibungsloser und die Risiken einer Inkompatibilität mit Hosts minimiert.



NOTE: Diese Funktion ist nur für Upgrade-Verträge mit SupportEdge Advisor, SupportEdge Expert und Digital Advisor verfügbar.

.Schritte
. Klicken Sie im Widget *Inventory* auf *Virtuelle Maschinen*, um die in Cloud Insights verfügbaren Daten anzuzeigen.
. Klicken Sie auf die Registerkarte *Virtual Machine Overview*.
. Klicken Sie auf die Schaltfläche *Anzahl der ESX Hosts*, um Informationen über den Host anzuzeigen.
. Klicken Sie auf den *ESX-Namen*, um zu Cloud Insights zu navigieren, um weitere Informationen anzuzeigen.

