---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Schutz der Systeme vor Ransomware-Risiken
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie sich beim Digital Advisor anmelden, können Sie die im Widget *Sicherheit & Ransomware Defense* hervorgehobenen *Aktionen* anzeigen, die die Risikozählungen anzeigen.

Sie können die Risiken von Snapshot-Erstellung, -Aufbewahrung und -ONTAP einsehen und dann Maßnahmen ergreifen, um sie zu beheben.

.Schritte
. Melden Sie sich bei Digital Advisor an.
. Klicken Sie im Widget *Sicherheit & Ransomware Defense* auf *Aktionen*.
. Deaktivieren Sie das Kontrollkästchen *Sicherheitsschwachstellen*.
. Überprüfen Sie die Auswirkungen auf die angezeigten Risiken und befolgen Sie die empfohlenen Maßnahmen.
. Klicken Sie auf die Registerkarte eindeutige Risiken und klicken Sie auf den Link in der Spalte *Korrekturmaßnahmen*.
. Klicken Sie auf die Registerkarte *Betroffene Systeme*, um Systeme mit Risiken anzuzeigen.
. Befolgen Sie Maßnahmen zur Problembehebung, die zum Schutz der Systeme empfohlen werden.

