---
sidebar: sidebar 
permalink: task_view_and_acknowledge_risks.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, acknowledge, unacknowledge, disregard 
summary: Bietet Informationen zur Anzeige und Analyse des Wohlbefindens Ihres Speichersystems und zur Anerkennung der Risiken. 
---
= Analysieren Sie die Wellness-Attribute im Digital Advisor und erkennen Sie die Risiken an.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Wellness-Attribute Ihres Storage-Systems analysieren, indem Sie sich die damit verbundenen Maßnahmen und Risiken anzeigen lassen. Sie sollten Korrekturmaßnahmen anzeigen und das Risiko manuell minimieren.

.Schritte
. Das Wellness-Attribut-Widget im Dashboard oder *Alle Aktionen anzeigen* ermöglicht die Anzeige der Liste aller Aktionen und Risiken.
. Sehen Sie sich die mit dem Wellness-Attribut verbundenen *Aktionen* und *Risiken* an.
. *Aktionen* zeigt die mit den Aktionen verbundenen Risiken an, *Risiken* zeigt alle Risiken an, und *Betroffene Systeme* zeigt die Systeme an, die Aufmerksamkeit erfordern.
. Das Risiko kann ausgewählt werden, um die Risikoübersicht anzuzeigen.
. *Bestätigen* auswählen, um das Risiko zu bestätigen.
+
Die detaillierten Informationen zur Risikoübersicht werden zusammen mit Korrekturmaßnahmen bereitgestellt, die manuell durchgeführt werden sollten, um das Risiko zu minimieren.

. Wenn das Risiko derzeit nicht gemindert werden soll oder kann, sind die Werte für die Felder anzugeben und *Bestätigen* auszuwählen.
+
Das Risiko wird zu anerkannten Risiken hinzugefügt.




NOTE: Wenn Sie nicht mehr möchten, dass ein Risiko bestätigt wird, kann das Risiko ignoriert werden, indem Sie *Bestätigung aufheben* auswählen und die gleichen Schritte ausführen.
