---
sidebar: sidebar 
permalink: task_view_performance_graphs.html 
keywords: performance, performance graph, graphs, digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level 
summary: Stellt Informationen zur Performance bereit. 
---
= Leistungsdiagramme des Speichersystems in Digital Advisor anzeigen.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Performance-Diagramme ermöglichen die Analyse der Performance Ihrer Speichergeräte. Sie können detaillierte Performance-Diagramme für ein ONTAP Cluster oder mehrere Nodes eines ONTAP Clusters und E-Series Controller anzeigen. Diese Diagramme bieten Verlaufsdaten zur Performance, die zum Verständnis der Performance-Trends und Musteranalysen verwendet werden können. Sie können ein Datum im Kalender auswählen, um Leistungsdiagramme für einen Tag, eine Woche, einen Monat, zwei Monate und zwölf Monate anzuzeigen. Sie können mehrere Nodes auswählen, um ein bestimmtes Diagramm gleichzeitig anzuzeigen.

Sie haben die Möglichkeit, Voreinstellungen festzulegen, beispielsweise können Sie entweder ein Diagramm für drei Knoten oder zwei Diagramme für drei Knoten anzeigen.

Beim ersten Anzeigen des Diagramms ist die Registerkarte „1 Woche“ vorausgewählt, und sie stellt die Daten einer Woche in einem grafischen Format dar, um große Datenmengen und deren Beziehungen zwischen verschiedenen Datenreihen leichter verständlich zu machen. Wenn der Datumsbereich zurückgesetzt werden soll, kann beispielsweise die Registerkarte „1 Monat“ ausgewählt und die Daten im Kalender gewählt werden.

Sie haben auch die Möglichkeit, das Performance-Diagramm zu vergrößern; die einzelnen Datenpunkte werden angezeigt.

video::fWrHYX17xT8[youtube,width=848,height=480]
.Schritte
. Im Dashboard die Option *Leistung* auswählen.
+
Bei ONTAP-Systemen kann die Registerkarte *Knoten* ausgewählt werden, um die Leistung eines einzelnen Knotens eines ONTAP Clusters anzuzeigen, die Registerkarte *Lokale Ebene*, um die Leistung der lokalen Ebene anzuzeigen, oder die Registerkarte *Volume*, um die Leistung des Volumes anzuzeigen. Standardmäßig wird die Clusterleistung angezeigt.

+
Für E-Series Systeme können Sie die Diagramme nur auf Controller-Ebene anzeigen.



. Wählen Sie entweder einen Tag, eine Woche, einen Monat, 2 Monate oder 12 Monate aus. Im Kalender zur Anzeige von Performancedaten im grafischen Format.
+
Wählen Sie beispielsweise die Registerkarte 2 Monate aus, um Daten für 2 Monate anzuzeigen. So können Sie je nach Ihren Performance-Anforderungen bestimmte Daten für eine Dauer anzeigen.

. Die folgenden Performance-Diagramme mit den erforderlichen Metriken sind für ONTAP Cluster und Nodes verfügbar:


[cols="25,25,25,25"]
|===
| Für Cluster | Für Node | Für Local Tier | Für Volume 


| IOPS | CPU-Auslastung – Spitzen-Performance (Reserve) | Durchschnittlicher Durchsatz | IOPS 


| Netzwerkdurchsatz | Latenz | Durchschnittliche Auslastung | Latenz 


|  | IOPS |  |  


|  | Protokoll-IOPS |  |  


|  | Netzwerkdurchsatz |  |  
|===
. Die folgenden Performance-Diagramme mit den erforderlichen Metriken sind für E-Series Controller verfügbar:
+
** CPU-Auslastung
** Latenz
** IOPS
** Durchsatz



