---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Schützen Sie von Digital Advisor verwaltete Speichersysteme vor Ransomware-Risiken
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie sich beim Digital Advisor anmelden, können Sie die im Widget *Sicherheit & Ransomware Defense* hervorgehobenen *Aktionen* anzeigen, die die Risikozählungen anzeigen.

Es besteht die Möglichkeit, die Risiken bei der Snapshot-Erstellung, -Aufbewahrung und der ONTAP FPolicy anzuzeigen und anschließend Maßnahmen zu deren Behebung zu ergreifen.

.Schritte
. Melden Sie sich bei Digital Advisor an.
. Im Widget *Security & Ransomware Defense* die Option *Actions* auswählen.
. Deaktivieren Sie das Kontrollkästchen *Sicherheitsschwachstellen*.
. Überprüfen Sie die Auswirkungen auf die angezeigten Risiken und befolgen Sie die empfohlenen Maßnahmen.
. Die Registerkarte *Besondere Risiken* auswählen und den Link in der Spalte *Korrekturmaßnahmen* auswählen.
. Die Registerkarte *Betroffene Systeme* zeigt Systeme mit Risiken an.
. Wählen Sie die empfohlenen Abhilfemaßnahmen zum Schutz der Systeme aus.

