---
sidebar: sidebar 
permalink: task_view_wellness_history.html 
keywords: wellness history, risks, wellness, view all actions, risk history 
summary: Bietet Informationen zu Systemrisiken und zur Anzeige der Wellness-Geschichte. 
---
= Sehen Sie sich die Risikohistorie Ihres Speichersystems in Digital Advisor an.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die in den letzten drei Monaten aufgetretenen Risiken für Speichersysteme einsehen, um zu erfahren, wie sie sich im Laufe der Zeit entwickeln.

Diese Risiken werden unter vier Arten von Risiken klassifiziert – *ungelöst*, *neu*, *gelöst* und *anerkannt*. Sie werden durch verschiedene Farben dargestellt. Die Zusammenfassung dieser Risiken wird durch einen *Risikoverlauf*-Diagramm dargestellt.

.Schritte
. Im Dashboard im Bereich *Wellness* die Option *Alle Aktionen anzeigen* auswählen.
. *Wellness-Historie* auswählen.
. Im Diagramm *Risikoverlauf* die Kategorie auswählen, für die der Risikoverlauf angezeigt werden soll.
+
Wenn Sie mit dem Mauszeiger über die farbigen Balken fahren, werden Informationen zur Anzahl der Risiken in jeder Kategorie angezeigt. Nach Auswahl der jeweiligen Risikokategorie werden die Informationen in der Tabelle *Risk Information* angezeigt.

+
Sie können die Risikoübersicht auch in einem Excel-Arbeitsblatt herunterladen.


