---
sidebar: sidebar 
permalink: task_view_risk_and_take_action.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, mitigate, rectify 
summary: Stellt Informationen zur Verfügung, mit denen Sie den Wellness-Bereich Ihres Storage-Systems anzeigen und analysieren und Risiken minimieren können. 
---
= Prüfen Sie die Risiken des Speichersystems im Digital Advisor und ergreifen Sie Korrekturmaßnahmen.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Wellness-Attribute Ihres Storage-Systems analysieren, indem Sie sich die damit verbundenen Maßnahmen und Risiken anzeigen lassen. Sie sollten die entsprechenden Korrekturmaßnahmen anzeigen und das Risiko manuell minimieren.

.Schritte
. Im Dashboard das Widget *Wellness* oder *Alle Aktionen anzeigen* auswählen, um die Liste aller Aktionen und Risiken anzuzeigen.
. Sehen Sie sich die mit dem Wellness-Attribut verbundenen *Aktionen* und *Risiken* an.
. *Aktionen* zeigt die mit den Aktionen verbundenen Risiken an, *Risiken* zeigt alle Risiken an, und *Betroffene Systeme* zeigt die Systeme an, die Aufmerksamkeit erfordern.
. Wählen Sie den Risikonamen aus, um Informationen zum Risiko anzuzeigen.
. Die zugehörigen Korrekturmaßnahmen auswählen und den Informationen folgen, um das Risiko zu beheben.


Die Schritte zur Minderung der Risiken sind für alle Wellness-Attribute gleich. Sie können das folgende Video anzeigen, um sicherheitsbezogene Probleme zu überwachen und zu beheben:

video::ssXI-FAKMis[youtube,width=848,height=480]