---
sidebar: sidebar 
permalink: task_view_API_catalog.html 
keywords: API Catalog, APIs, integrate data, view catalog 
summary: Liefert Informationen zu den im API-Katalog verfügbaren APIs. 
---
= API-Katalog zur Ausführung von APIs
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der API-Katalog ermöglicht das Durchsuchen von Kategorien und den verfügbaren APIs innerhalb jeder dieser Kategorien.

Mit einem gültigen Access Token und korrekten Eingaben für die erforderlichen Felder können Sie einen Testaufruf für eine API durchführen.



== Zugriff auf GraphQL-APIs

.Schritte
. Klicken Sie im Menü *Quick Links* auf *API Services*.
. Klickenlink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Durchsuchen"] unter dem Symbol *API-Katalog*.
+
Der API-Katalog wird angezeigt.

. Klicken Sie auf *GraphQL* und lesen Sie die Dokumentation.
. Testen Sie die GraphQL-APIs mit den sofort einsatzbereiten Beispielabfragen unterlink:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer?collectionId=251c50ce-797e-4549-bb9c-f6557ef5a176OPERATION_COLLECTIONfocusCollectionId=251c50ce-797e-4549-bb9c-f6557ef5a176["Digital Advisor GraphQL Studio"^] .
. Geben Sie ein Benutzertoken an, indem Sie das Autorisierungsfeld im Header der API-Anfrage auswählen
. Geben Sie die erforderlichen Variablen an
. Führen Sie die Abfrage aus und überprüfen Sie die Ausgabe




== Zugriff auf REST-APIs

.Schritte
. Klicken Sie im Menü *Quick Links* auf *API Services*.
. Klickenlink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Durchsuchen"] unter dem Symbol *API-Katalog*.
+
Der API-Katalog wird angezeigt.

. Klicken Sie auf *ActiveIQ-Public* und wählen Sie eine beliebige API aus
. Schieben Sie oben auf der Seite den Schalter auf „Experiment“.
. Erweitern Sie in der linken Navigation die Kategorien und wählen Sie eine beliebige API, um detaillierte Informationen anzuzeigen.
. Erweitern Sie die API.
. Klicken Sie rechts auf die Schaltfläche *Try it out*.
. Geben Sie die erforderlichen Parameter ein und klicken Sie zum Anzeigen der Ergebnisse auf *Ausführen*.
+
Sie können auch den Abschnitt *Antworten* der API untersuchen, um die Daten zu verstehen, die besser zurückgegeben werden. Klicken Sie auf *Beispielwert*, um das Format der Daten anzuzeigen, oder klicken Sie auf *Modell* und klicken Sie auf die Carets, um die Abschnitte zu erweitern, um die Definition jedes Elements anzuzeigen.



Wenn Sie den Schalter in die *Code*-Ansicht schieben, können Sie Codebeispiele in verschiedenen Sprachen anzeigen.
