---
sidebar: sidebar 
permalink: task_execute_ansible_playbook_without_docker.html 
keywords: Ansible Playbook, Ansible, playbook, without docker 
summary: Enthält Informationen zum Ausführen des Ansible-Playbooks über das Docker-Image. 
---
= Ansible Playbook ohne NetApp Docker Image ausführen
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.Schritte
[role="lead"]
. Installieren link:https://docs.python.org/3/using/windows.html["Python"] Und link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Ansible"].
. Installieren Sie die erforderlichen Python-Pakete mit *pip*:
+
[listing]
----
$ pip install netapp-lib requests paramiko
 
Installing collected packages: netapp-lib, requests, paramiko
Successfully installed netapp-lib-2020.3.12 requests-2.23.0  paramiko-2.7.2
----
. Installation der NetApp Ansible-Sammlung mit dem Befehl *ansible-Galaxie*:
+
[listing]
----
To install the collection only for the current user
$ ansible-galaxy collection install netapp.ontap
 
To do a more universal installation,
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections

$ chmod -R +rw /usr/share/ansible/collections
----
+
Weitere Informationen zum ansible-Galaxie-Befehl finden Sie unter link:https://docs.ansible.com/ansible/latest/cli/ansible-galaxy.html["Ansible-Galaxy-Dokumentation"] Weitere Informationen zur NetApp Ansible Sammlung finden Sie im link:https://galaxy.ansible.com/netapp/ontap["NetApp Ansible Collection-Seite"].

. Ansible Playbook mit dem Befehl *ansible-Playbook* ausführen:
+
[listing]
----
$ cd <downloaded_playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml
 
Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
+

NOTE: Wenn es eine Reihe von Clustern mit unterschiedlichen Anmeldedaten gibt, muss das Ansible Playbook auf jedem Cluster ausgeführt werden. Die Bestandsdatei muss nicht geändert werden, da das Ansible Playbook die Cluster überspringt, für die die Anmeldung fehlgeschlagen ist.



Weitere Informationen zum Befehl *ansible-Playbook* finden Sie im link:https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html["Ansible Playbook-Dokumentation"] Informationen zum Ausführen des Ansible Playbook im Check-Modus (Dry Run) finden Sie unter link:https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html["Ansible: Prüfen Sie den Modus"].

Lesen Sie nach dem Ausführen des Playbooks das link:task_validate_firmware_installation.html["Validieren Der Firmware-Installation"] Für Anweisungen nach der Ausführung.
