---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: Stellt Informationen zum Gesamtbestand bereit, zu dem Sie gehören. 
---
= Sehen Sie sich die Inventardetails Ihres Speichersystems in Digital Advisor an.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das Widget *Inventar* bietet Ihnen eine Übersicht über alle Systeme und die Switches mit Supportberechtigung, die Sie besitzen.  Dies umfasst sowohl Digital Advisor -fähige als auch nicht-fähige Produkte.

Sie können auch den Bericht der ausgewählten Watchlist generieren und den Bericht an maximal 5 Empfänger senden.

video::ttbpbT5uTBI[youtube,width=848,height=480]


== Zeigen Sie Systemdetails an

.Schritte
. Klicken Sie im Widget *Inventory* auf *Systems*, um die Systeminformationen aller Plattformen anzuzeigen, oder klicken Sie auf den Plattformtyp und klicken Sie dann auf *Systems*, um die für diese Plattform spezifischen Systeme anzuzeigen.
. Klicken Sie auf den Node oder Cluster, um detaillierte Informationen über das System anzuzeigen.
. Laden Sie den Bericht *Inventory* herunter, um die Systemdetails im XLS-Format anzuzeigen.
. Laden Sie den Bericht *Ansible Inventory* herunter, um die Systemdetails im Format .yml und .ini auf Region- oder Standortebene anzuzeigen.
+
Die Ansible-Bestandsdateien können mit benutzerdefinierten Ansible-Playbook-Dateien verwendet werden, um eine Änderung der Infrastrukturkonfiguration vorzunehmen.





== Details zum Support-berechtigten Switch anzeigen

.Schritte
. Klicken Sie im Widget *Inventar* auf *Supportberechtigte Switches*, um Informationen zu allen supportberechtigten Switches anzuzeigen.

