---
sidebar: sidebar 
permalink: view_keystone_capacity_utilization.html 
keywords: keystone, capacity utilization, service tiers, Keystone subscription, keystone subscription, shares, disks 
summary: Bietet Informationen zu Ihrer Kapazitätsauslastung mit einem NetApp Keystone-Abonnement. 
---
= Anzeige der Kapazitätsauslastung mit NetApp Keystone-Abonnement
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Wenn Sie den Keystone Subscription Service abonniert haben, können Sie das Keystone Abonnement-Widget auf dem Digital Advisor Dashboard anzeigen.

Das Keystone Abonnement-Widget bietet Ihnen einen Überblick über die Kapazitätsnutzung für Ihr Konto. Es besteht aus Kapazitätsnutzungsdiagramme mit Bezug auf die physische Kapazität, wobei der Snapshot auf die letzten fünf Minuten aufgerundet wird. Die Auslastung über und über der zugesagt Kapazität (die Burst-Kapazität) wird rot markiert.

Sie können sich das Dashboard *Keystone - Capacity Utiliage* ansehen, das die Daten im Widget analysiert und grafisch den Nutzungstrend der Kapazität und Nutzung für den gesamten abonnierten Speicher darstellt link:https://docs.netapp.com/us-en/keystone/nkfsosm_performance.html["Service-Tiers"^], Wie Premium, extrem, und Standard, mit Ihrem NetApp Keystone-Abonnement-Konto verbunden.

Sie können die anzeigen link:https://docs.netapp.com/us-en/keystone/nkfsosm_keystone_service_capacity_definitions.html["Kapazität des Keystone Abonnement-Services"^] Die Nutzung der einzelnen abonnierten Services für Ihren Block-, File-Services- oder Objekt-Storage im Dashboard.


NOTE: Als Digital Advisor-Benutzer können Sie zwischen ONTAP Collector und AutoSupport wählen, um Daten zur Kapazitätsnutzung zu erhalten.

Weitere Informationen zum Keystone-Abonnement finden Sie unter link:https://docs.netapp.com/us-en/keystone-staas/integrations/aiq-keystone-details.html["Keystone Abonnement-Dashboard und Berichterstellung"^].
