---
sidebar: sidebar 
permalink: view-firmware-update-recommendations.html 
keywords: upgrade advisor, firmware recommendations, storage firmware, sp bmc firmware, system files, security files 
summary: Aktualisierungsempfehlungen für Speicher-Firmware, SP/BMC-Firmware, Systemdateien und Sicherheitsdateien einsehen. 
---
= Empfehlungen für Firmware-Updates finden Sie im Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Kunden können jetzt Zeit und Aufwand sparen, da Control Tower ihre Systeme automatisch mit den neuesten Firmware-Versionen aktualisieren kann, sodass kein manuelles Eingreifen oder eine manuelle Planung erforderlich ist. Dieses Update reduziert das Risiko, dass Probleme aufgrund veralteter oder inkompatibler Firmware-Versionen auftreten, und sorgt so für optimale Systemleistung, Stabilität und Sicherheit.

Kunden erhalten zeitnah Benachrichtigungen und Warnungen über den Status der Firmware-Updates. Es stehen Optionen zur Aktivierung von AutoSupport und Auto-Update-Einstellungen zur Verfügung.

.Schritte
. Auf der Dashboard-Seite im Widget *Upgrade Advisor* ist *Weitere Empfehlungen* auszuwählen.
. *Empfehlungen anzeigen* auswählen, um die Liste der Empfehlungen anzuzeigen.
. In der Spalte *Update Status* die Option *Fortschritt anzeigen* auswählen, um die Cluster anzuzeigen, die für ein Update in Frage kommen.
. Bei Problemen können die jeweiligen Links ausgewählt werden, um die Schritte zur Behebung der Probleme anzuzeigen.

